version: '3.2'

services:
  web:
    build: .
    image: $LOCAL_IMAGE_ID

    # Install dependencies in the current container for test.
    # Not in the original image
    volumes:
      - ./node_modules:/node_modules

    tty: true
    command: npm install && npm run test:all